name: GTG Manual Re-run

# Manual trigger only - for re-running GTG without full CI rebuild
# Use this when threads are resolved and you want a quick GTG re-check
#
# Copy this file to .github/workflows/gtg.yml in your project.
# See: https://github.com/dsifry/goodtogo

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number to check"
        required: true
        type: number

permissions:
  pull-requests: read
  contents: read
  checks: read
  statuses: read

jobs:
  gtg-check:
    name: Merge Ready (gtg)
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install gtg
        run: |
          pip install gtg || {
            echo "::error::Failed to install gtg from PyPI"
            exit 1
          }

      - name: Check PR readiness
        env:
          GITHUB_TOKEN: ${{ secrets.GTG_PAT }}
        run: |
          set -o pipefail
          echo "Checking PR #${{ github.event.inputs.pr_number }} readiness..."

          set +e
          gtg ${{ github.event.inputs.pr_number }} \
            --repo ${{ github.repository }} \
            --semantic-codes \
            --format text \
            --verbose \
            --exclude-checks "Merge Ready (gtg)" \
            --exclude-checks "CodeRabbit" 2>&1 | tee gtg-output.txt
          EXIT_CODE=${PIPESTATUS[0]}
          set -e

          echo "::group::GTG Check Details"
          cat gtg-output.txt
          echo "::endgroup::"

          case $EXIT_CODE in
            0)
              echo "::notice::PR #${{ github.event.inputs.pr_number }} is ready to merge"
              ;;
            1)
              echo "::error::PR has actionable comments that need to be addressed"
              exit 1
              ;;
            2)
              echo "::error::PR has unresolved review threads"
              exit 2
              ;;
            3)
              echo "::error::PR has failing CI checks"
              exit 3
              ;;
            4)
              echo "::error::Error fetching PR data from GitHub API"
              exit 4
              ;;
            *)
              echo "::error::GTG check failed with unexpected exit code: $EXIT_CODE"
              exit $EXIT_CODE
              ;;
          esac
